version: "3.8"

services:
  backend:
    container_name: zero-to-prod-app
    image: zero-to-prod-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8000:8000
      # - '8080-8085:8080'
    environment:
      - APP_DATABASE__HOST=postgres-db
      - APP_DATABASE__PORT=5432
      - APP_DATABASE__USERNAME=app
      - APP_DATABASE__PASSWORD=secret
      - APP_DATABASE__DATABASE_NAME=newsletter
      - APP_DATABASE__REQUIRE_SSL=false
      - APP_APPLICATION__BASE_URL=0.0.0.0:8000
      - APP_REDIS_URI=redis://redis-db
    volumes:
      - ./src:/usr/src/app/src
    restart: unless-stopped
    networks:
      - backend_network
    depends_on:
      - postgres
      - redis
    # deploy:
    #   replicas: 4

  postgres:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=newsletter
    networks:
      - backend_network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  redis:
    container_name: redis-db
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data: {}
