services:
  # A Docker web service
  - type: web
    runtime: docker
    name: zero2prod
    numInstances: 1 # optional (defaults to 1)
    region: frankfurt # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    branch: main # optional (defaults to master)
    rootDir: .
    autoDeploy: true
    healthCheckPath: /health-check
    envVars:
      - key: APP_DATABASE__USERNAME
        fromDatabase:
          name: newsletter
          property: user
      - key: APP_DATABASE__PASSWORD
        fromDatabase:
          name: newsletter
          property: password
      - key: APP_DATABASE__HOST
        fromDatabase:
          name: newsletter
          property: host
      - key: APP_DATABASE__PORT
        fromDatabase:
          name: newsletter
          property: port
      - key: APP_DATABASE__DATABASE_NAME
        fromDatabase:
          name: newsletter
          property: database

databases:
  - name: newsletter
    region: frankfurt
    postgresMajorVersion: "12"
    plan: free
